export const initialProducts = [
  {
    title: 'Animi Dolor Pariatur',
    slug: 'animi-dolor-pariatur',
    category: 'decoration',
    price: 15000,
    delPrice: 28500,
    image: '/assets/images/product-1.jpg',
    badge: 'Sale',
    badgeColor: 'orange',
    cardBadge: null,
    inStock: true,
    stockQuantity: 25,
    description: 'Sculptural ceramic modern decor ornament hand-finished with artisan glaze. Elevates living spaces, office desks, and consoles.',
    dimensions: '20cm x 15cm x 28cm',
    material: 'Glazed Ceramic',
    rating: 5,
    reviewsCount: 18,
    isFeatured: true,
  },
  {
    title: 'Art Deco Home',
    slug: 'art-deco-home',
    category: 'accessory',
    price: 45000,
    delPrice: null,
    image: '/assets/images/product-2.jpg',
    badge: null,
    badgeColor: null,
    cardBadge: 'Out of Stock',
    inStock: false,
    stockQuantity: 0,
    description: 'Art Deco inspired geometric accent vessel. Distinctive timeless luxury for minimalist and classic architectural interiors.',
    dimensions: '30cm x 18cm',
    material: 'Porcelain & Brass',
    rating: 4.8,
    reviewsCount: 9,
    isFeatured: true,
  },
  {
    title: 'Artificial potted plant',
    slug: 'artificial-potted-plant',
    category: 'decoration',
    price: 60000,
    delPrice: 84000,
    image: '/assets/images/product-3.jpg',
    badge: '-25%',
    badgeColor: 'cyan',
    cardBadge: null,
    inStock: true,
    stockQuantity: 40,
    description: 'Ultra-realistic botanical foliage potted in a minimalist concrete planter. Zero maintenance with lifelike textures.',
    dimensions: '45cm height',
    material: 'Eco-polyester & Concrete Planter',
    rating: 4.9,
    reviewsCount: 32,
    isFeatured: true,
  },
  {
    title: 'Dark Green Jug',
    slug: 'dark-green-jug',
    category: 'accessory',
    price: 25500,
    delPrice: null,
    image: '/assets/images/product-4.jpg',
    badge: null,
    badgeColor: null,
    cardBadge: null,
    inStock: true,
    stockQuantity: 18,
    description: 'Deep forest green stoneware pitcher with ergonomic handle and spill-proof spout. Suitable for beverages or dried floral arrangements.',
    dimensions: '1.5 Liters, 24cm height',
    material: 'Stoneware',
    rating: 4.7,
    reviewsCount: 14,
    isFeatured: false,
  },
  {
    title: 'Drinking Glasses',
    slug: 'drinking-glasses',
    category: 'accessory',
    price: 31500,
    delPrice: null,
    image: '/assets/images/product-5.jpg',
    badge: null,
    badgeColor: null,
    cardBadge: null,
    inStock: true,
    stockQuantity: 30,
    description: 'Set of 4 hand-blown crystal glassware with subtle tactile fluting. Dishwasher safe and engineered for cocktail or dining presentation.',
    dimensions: '350ml per glass',
    material: 'Lead-free Crystal Glass',
    rating: 4.9,
    reviewsCount: 22,
    isFeatured: false,
  },
  {
    title: 'Helen Chair',
    slug: 'helen-chair',
    category: 'furniture',
    price: 104000,
    delPrice: null,
    image: '/assets/images/product-6.jpg',
    badge: 'Sale',
    badgeColor: 'orange',
    cardBadge: null,
    inStock: true,
    stockQuantity: 12,
    description: 'Ergonomic dining and accent chair featuring curved backrest support and high-density foam cushioning upholstered in textured linen.',
    dimensions: '82cm H x 54cm W x 56cm D',
    material: 'Solid Ash Wood & Textured Linen',
    rating: 5,
    reviewsCount: 45,
    isFeatured: true,
  },
  {
    title: 'High Quality Glass Bottle',
    slug: 'high-quality-glass-bottle',
    category: 'accessory',
    price: 45000,
    delPrice: 69000,
    image: '/assets/images/product-7.jpg',
    badge: '-35%',
    badgeColor: 'cyan',
    cardBadge: null,
    inStock: true,
    stockQuantity: 20,
    description: 'Heavyweight amber artisan glass decanter with precision ground stopper. Protects aromatic oils, spirits, or acts as an artistic sculpture.',
    dimensions: '750ml, 28cm height',
    material: 'Hand-molded Amber Glass',
    rating: 4.6,
    reviewsCount: 8,
    isFeatured: false,
  },
  {
    title: 'Living Room & Bedroom Lights',
    slug: 'living-room-bedroom-lights',
    category: 'decoration',
    price: 67500,
    delPrice: null,
    image: '/assets/images/product-8.jpg',
    badge: null,
    badgeColor: null,
    cardBadge: null,
    inStock: true,
    stockQuantity: 15,
    description: 'Modern pendant lighting fixture casting warm diffuse illumination. Comes with adjustable suspension cable and LED bulb included.',
    dimensions: '35cm diameter shade',
    material: 'Powder-coated Matte Steel & Frosted Glass',
    rating: 4.8,
    reviewsCount: 19,
    isFeatured: true,
  },
  {
    title: 'Nancy Chair',
    slug: 'nancy-chair',
    category: 'furniture',
    price: 135000,
    delPrice: null,
    image: '/assets/images/product-9.jpg',
    badge: null,
    badgeColor: null,
    cardBadge: null,
    inStock: true,
    stockQuantity: 8,
    description: 'Plush mid-century modern armchair crafted with sustainable oak frame and boucle upholstery. Perfect statement piece for lounges.',
    dimensions: '88cm H x 76cm W x 78cm D',
    material: 'Solid White Oak & Boucle Fabric',
    rating: 5,
    reviewsCount: 27,
    isFeatured: true,
  },
  {
    title: 'Simple Chair',
    slug: 'simple-chair',
    category: 'furniture',
    price: 60000,
    delPrice: null,
    image: '/assets/images/product-10.jpg',
    badge: null,
    badgeColor: null,
    cardBadge: null,
    inStock: true,
    stockQuantity: 16,
    description: 'Clean Scandinavian lines define this minimalist side chair. Stackable, durable, and suited for high-traffic dining spaces.',
    dimensions: '79cm H x 48cm W x 50cm D',
    material: 'Molded Beech Plywood',
    rating: 4.7,
    reviewsCount: 16,
    isFeatured: false,
  },
  {
    title: 'Smooth Disk',
    slug: 'smooth-disk',
    category: 'decoration',
    price: 69000,
    delPrice: null,
    image: '/assets/images/product-11.jpg',
    badge: null,
    badgeColor: null,
    cardBadge: null,
    inStock: true,
    stockQuantity: 14,
    description: 'Circular architectural table sculpture carved from natural travertine limestone. Mounted on an elevated dark steel plinth.',
    dimensions: '32cm diameter x 6cm depth',
    material: 'Natural Travertine & Steel',
    rating: 4.9,
    reviewsCount: 11,
    isFeatured: false,
  },
  {
    title: 'Table Black',
    slug: 'table-black',
    category: 'furniture',
    price: 100500,
    delPrice: null,
    image: '/assets/images/product-12.jpg',
    badge: null,
    badgeColor: null,
    cardBadge: null,
    inStock: true,
    stockQuantity: 10,
    description: 'Monochromatic ebony stained coffee table with beveled edges and conical cylindrical legs. Water and scratch-resistant matte lacquer.',
    dimensions: '110cm L x 60cm W x 42cm H',
    material: 'Solid Oak & Stained Veneer',
    rating: 4.8,
    reviewsCount: 24,
    isFeatured: true,
  },
  {
    title: 'Table Wood Pine',
    slug: 'table-wood-pine',
    category: 'furniture',
    price: 75000,
    delPrice: null,
    image: '/assets/images/product-13.jpg',
    badge: null,
    badgeColor: null,
    cardBadge: null,
    inStock: true,
    stockQuantity: 14,
    description: 'Natural pine console table highlighting organic grain patterns and joinery details. Ideal for entryways, hallways, or behind sofas.',
    dimensions: '120cm L x 35cm W x 76cm H',
    material: 'Kiln-dried Solid Pine',
    rating: 4.9,
    reviewsCount: 31,
    isFeatured: true,
  },
  {
    title: 'Teapot with black tea',
    slug: 'teapot-with-black-tea',
    category: 'accessory',
    price: 37500,
    delPrice: 48000,
    image: '/assets/images/product-14.jpg',
    badge: '-20%',
    badgeColor: 'cyan',
    cardBadge: null,
    inStock: true,
    stockQuantity: 22,
    description: 'Traditional Japanese-style cast iron Tetsubin teapot with interior enamel coating and removable stainless steel mesh infuser.',
    dimensions: '900ml capacity',
    material: 'Cast Iron with Enamel Lining',
    rating: 4.9,
    reviewsCount: 19,
    isFeatured: false,
  },
  {
    title: 'Unique Decoration',
    slug: 'unique-decoration',
    category: 'decoration',
    price: 22500,
    delPrice: null,
    image: '/assets/images/product-15.jpg',
    badge: null,
    badgeColor: null,
    cardBadge: null,
    inStock: true,
    stockQuantity: 35,
    description: 'Handcrafted abstract geometric tabletop accessory. A bold modern accent for bookcases, console styling, or office decor.',
    dimensions: '18cm x 18cm x 22cm',
    material: 'Terracotta Ceramic',
    rating: 4.6,
    reviewsCount: 13,
    isFeatured: false,
  },
  {
    title: 'Vase Of Flowers',
    slug: 'vase-of-flowers',
    category: 'decoration',
    price: 115500,
    delPrice: null,
    image: '/assets/images/product-16.jpg',
    badge: 'Sale',
    badgeColor: 'orange',
    cardBadge: null,
    inStock: true,
    stockQuantity: 11,
    description: 'Tall fluted ceramic floor vase with organically textured surface. Designed to hold tall stems or make an architectural solo statement.',
    dimensions: '60cm H x 22cm W',
    material: 'Heavy Ceramic',
    rating: 5,
    reviewsCount: 21,
    isFeatured: true,
  },
  {
    title: 'Wood Eggs',
    slug: 'wood-eggs',
    category: 'decoration',
    price: 28500,
    delPrice: null,
    image: '/assets/images/product-17.jpg',
    badge: null,
    badgeColor: null,
    cardBadge: null,
    inStock: true,
    stockQuantity: 28,
    description: 'Set of 3 hand-turned solid hardwood decorative eggs presented in a natural wood display cradle. Smooth tactile satin oil finish.',
    dimensions: '9cm x 6cm each',
    material: 'Turned Teak & Walnut Wood',
    rating: 4.8,
    reviewsCount: 17,
    isFeatured: false,
  },
  {
    title: 'Wooden Box',
    slug: 'wooden-box',
    category: 'accessory',
    price: 40500,
    delPrice: 58500,
    image: '/assets/images/product-18.jpg',
    badge: '-30%',
    badgeColor: 'cyan',
    cardBadge: null,
    inStock: true,
    stockQuantity: 19,
    description: 'Dovetail-joined keepsake storage box with soft velvet interior lining and brushed brass recessed handle. Ideal for watches and jewelry.',
    dimensions: '26cm x 18cm x 10cm',
    material: 'Solid Walnut & Brushed Brass',
    rating: 4.9,
    reviewsCount: 29,
    isFeatured: false,
  },
  {
    title: 'Wooden Cups',
    slug: 'wooden-cups',
    category: 'accessory',
    price: 43500,
    delPrice: null,
    image: '/assets/images/product-19.jpg',
    badge: null,
    badgeColor: null,
    cardBadge: null,
    inStock: true,
    stockQuantity: 24,
    description: 'Set of 2 carved jujube wood tea tumblers. Naturally insulating, lightweight, and coated with food-safe plant lacquer.',
    dimensions: '250ml each',
    material: 'Natural Jujube Hardwood',
    rating: 4.7,
    reviewsCount: 15,
    isFeatured: false,
  },
];

export const initialBusinessInfo = {
  storeName: 'Romadec Stores',
  shortName: 'Romadec',
  tagline: 'Get Quality Furniture',
  email: 'support@romadec.com',
  phone: '+234 (0) 808 760 8827',
  address: '93 Olojo Drive, Ojo, Lagos, Nigeria',
  city: 'Victoria Island, Lagos',
  state: 'Lagos',
  country: 'Nigeria',
  currency: 'NGN',
  currencySymbol: '₦',
  aboutText:
    'Modern & Luxury Turkish Furniture. Timeless designs to suit any style of interior design. Worldwide Delivery. Est. in 1994.',
  videoUrl: '',
  socialLinks: {
    facebook: 'https://facebook.com/romadec',
    twitter: 'https://twitter.com/romadec',
    instagram: 'https://instagram.com/romadec',
  },
};
